// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZK4xL6VAaXLZJ7J4_A4hK77Vror0qWg',
    appId: '1:485410223126:web:57a0bc07c93783bf073137',
    messagingSenderId: '485410223126',
    projectId: 'flutterauthapp1-66b7f',
    authDomain: 'flutterauthapp1-66b7f.firebaseapp.com',
    storageBucket: 'flutterauthapp1-66b7f.firebasestorage.app',
    measurementId: 'G-VD26QP5Y0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5Tlion9GXFQqRJuowFPcuaCHyzyWlOg',
    appId: '1:485410223126:android:114d95d4fa180640073137',
    messagingSenderId: '485410223126',
    projectId: 'flutterauthapp1-66b7f',
    storageBucket: 'flutterauthapp1-66b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oYKF_G2UhkgTn9kDoiU5unCDy5xnbvk',
    appId: '1:485410223126:ios:30a947bd6cf76c7f073137',
    messagingSenderId: '485410223126',
    projectId: 'flutterauthapp1-66b7f',
    storageBucket: 'flutterauthapp1-66b7f.firebasestorage.app',
    iosBundleId: 'com.example.myAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4oYKF_G2UhkgTn9kDoiU5unCDy5xnbvk',
    appId: '1:485410223126:ios:30a947bd6cf76c7f073137',
    messagingSenderId: '485410223126',
    projectId: 'flutterauthapp1-66b7f',
    storageBucket: 'flutterauthapp1-66b7f.firebasestorage.app',
    iosBundleId: 'com.example.myAuthProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnZK4xL6VAaXLZJ7J4_A4hK77Vror0qWg',
    appId: '1:485410223126:web:e031f13fa85cb3ea073137',
    messagingSenderId: '485410223126',
    projectId: 'flutterauthapp1-66b7f',
    authDomain: 'flutterauthapp1-66b7f.firebaseapp.com',
    storageBucket: 'flutterauthapp1-66b7f.firebasestorage.app',
    measurementId: 'G-PDWFFDQ0TL',
  );
}
